spring.application.name=employeemanagement
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=my-secret-pw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080